export const personalInfo = {
  name: "Sjaaf Rhisjad Daud Djavatri",
  title: "Fullstack IT Programmer",
  bio: "Versatile Fullstack Developer with extensive experience architecting and building end-to-end applications across diverse technology stacks. Proficient in Node.js, NestJS, Go, PHP, Next.js, and Svelte, with a strong foundation in both frontend interfaces and scalable backend microservices. Adaptable and fast-learning, I am passionate about tackling complex problems—from real-time WebSockets and asynchronous messaging queues to GPS geofencing and mobile hardware integrations.",
  summary: "Passionate and results-driven Fullstack Developer with a proven track record of delivering high-impact software solutions. Highly proficient in modern backend frameworks (NestJS, Go/Gin, Node.js, PHP CodeIgniter) and frontend ecosystems (Svelte 5, Next.js, React, Kotlin/Jetpack Compose). I excel at architecting scalable microservices, implementing real-time communication (Socket.io, RabbitMQ), integrating third-party APIs (WAHA, Jatis, Google Maps), and building comprehensive enterprise dashboards with complex workflows like multi-tier approvals and geofencing. A collaborative team player known for taking ownership of ambitious projects and modernizing system architectures.",
  whatIDo: [
    "Architect and build scalable microservices & RESTful APIs",
    "Develop comprehensive web platforms and HRIS dashboards",
    "Implement real-time features using WebSockets & message queues",
    "Design responsive frontend interfaces (SvelteKit, Next.js)",
    "Integrate third-party services (WhatsApp APIs, LLMs, S3, Maps)",
    "Build native Android applications with hardware integration",
  ],
};

export const experiences = [
  {
    id: 1,
    role: "Fullstack Developer",
    company: "PT. K-Link Nusantara",
    period: "2023 - Present",
    description: "Worked on maintaining and improving e-commerce platforms and internal tools by refactoring backend services to enhance performance and reliability. Led the development of a new international application, including an admin dashboard and bonus calculation system. Optimized database queries and built automated data processing using scheduled scripts and ETL workflows. Collaborated closely with data warehouse and business analyst teams to ensure data accuracy, and created technical documentation for data pipelines and processes. Also developed backend messaging services in Golang supporting WhatsApp, Email, Telegram, and other channels.",
    skills: ["React", "Node.js", "Nest.js", "Next.js", "Express.js", "Golang", "PostgreSQL", "MySQL", "Typescript/Javascript", "Git", "Tailwind CSS", "Prisma", "TypeORM", "Sequelize", "PHP"],
  },
  {
    id: 2,
    role: "Freelance Developer",
    company: "Self-employed",
    period: "2023 - Present",
    description: "Developed and maintained multiple web applications, implemented new features, and conducted code reviews.",
    skills: ["React", "Node.js", "Next.js", "Nest.js", "Express.js", "MongoDB", "PostgreSQL", "MySQL", "Docker", "Git", "Tailwind CSS", "Typescript/Javascript", "Railway", "Prisma", "TypeORM", "Sequelize", "Docker"],
  },
  {
    id: 3,
    role: "Head of Barista - Supervisor",
    company: "PT. Roemah Kita Boga",
    period: "2019 - 2023",
    description: "Maintaining and improving bar product and stock, and ensuring quality control and customer satisfaction, managing 15+ employees., responsible for purchasing and inventory management.",
    skills: ["Highest Revenue", "Latte Art"],
  },
];

export const education = [
  {
    id: 1,
    degree: "Bootcamp - Full Stack Developer",
    institution: "Dumbways.id",
    period: "2023",
    description: "Intensive 20-week program covering modern web development technologies.",
    achievements: ["Top Performer", "Published 3 projects"],
  },
  {
    id: 2,
    degree: "Bachelor's Degree in Management",
    institution: "Gunadarma University",
    period: "2018 - 2019",
    description: "Unfinished due to financial issues.",
    achievements: [],
  },
  {
    id: 3,
    degree: "High School Diploma",
    institution: "1 High School Kendari",
    period: "2015 - 2018",
    description: "Completed with honors.",
    achievements: ["Art Club President", "Futsal Team Captain", "Passed to College Benefit Program"],
  },
];

export const skillsData = {
  hardSkills: [
    { name: "JavaScript/TypeScript", level: 95 },
    { name: "React & Next.js", level: 92 },
    { name: "Node.js, Nest.js, Express", level: 95 },
    { name: "Database Design (SQL/NoSQL)", level: 92 },
    { name: "REST APIs & GraphQL", level: 95 },
    { name: "HTML & CSS/Tailwind", level: 94 },
    { name: "Git & Version Control", level: 92 },
    { name: "Golang", level: 88 },
    { name: "PHP", level: 85 },
    { name: "Kotlin", level: 80 },
    { name: "Svelte 5 / SvelteKit", level: 85 },
    { name: "AWS", level: 80 },
    { name: "WebSockets", level: 80 },
    { name: "RabbitMQ", level: 85 },
    { name: "Redis", level: 80 },
  ],
  softSkills: [
    "Problem Solving",
    "Team Collaboration",
    "Communication",
    "Project Management",
    "Adaptability",
    "Attention to Detail",
    "Continuous Learning",
    "Time Management",
    "Critical Thinking",
    "Business Analysis",
    "Loyalty"
  ],
};

export const projects = [
  {
    title: "K-Link HRIS (Human Resource Information System)",
    company: "K-Link Indonesia",
    description: "Developed a comprehensive HRIS frontend using Svelte 5 and SvelteKit. Built complex modules including GPS-geofenced attendance tracking with Leaflet maps, multi-tier approval workflows, custom WYSIWYG editors, and full bilingual i18n support.",
    tags: ["Svelte 5", "SvelteKit", "TypeScript", "TailwindCSS v4", "Leaflet", "i18n"],
    link: "#",
    github: "https://github.com/K-Link-Indonesia/klink-hris",
  },
  {
    title: "Customer Service Dashboard Backend",
    company: "K-Link Indonesia",
    description: "Developed a Customer Service Dashboard backend using NestJS, Prisma, and PostgreSQL. Engineered real-time chat functionalities with WebSockets (Socket.io) and implemented features such as scheduled messages, pinned chats, message templates, internal webhooks, and AWS S3 integration for media handling.",
    tags: ["NestJS", "Prisma", "PostgreSQL", "Socket.io", "AWS S3", "WebSockets", "REST API"],
    link: "#",
    github: "https://github.com/K-Link-Indonesia/backend-dashboard-customer-service",
  },
  {
    title: "Ionation Kiosk Mobile App",
    company: "Freelance",
    description: "Developed a native Android kiosk application using Kotlin and Jetpack Compose. Features include real-time API integration with Retrofit for authentication and activity scoring, and custom Bluetooth thermal printing with dynamic off-screen bitmap rendering and image blending.",
    tags: ["Kotlin", "Android", "Jetpack Compose", "Retrofit", "Bluetooth Printing"],
    link: "#",
    github: "https://github.com/icaddddd/samakami_mobile_kotlin",
  },
  {
    title: "Ticketing Registration",
    company: "Freelance",
    description: "Web-based event registration service with ticket generation and send via Email.",
    tags: ["Next.js", "TypeScript", "PostgreSQL", "Prisma", "Tailwind CSS", "shadcn", "EmailJS"],
    link: "#",
    github: "https://github.com/icaddddd/samakami_games",
  },
  {
    title: "DNM Mobile Backend Microservice (E-commerce)",
    company: "K-Link Indonesia",
    description: "Maintained and optimized backend microservices for the DNM mobile application using Node.js and Express.js to improve system reliability.",
    tags: ["Node.js", "Express.js"],
    link: "#",
    github: "https://github.com/K-Link-Indonesia/dnm-backend-order-service",
  },
  {
    title: "Warehouse Management System",
    company: "K-Link Indonesia",
    description: "Maintained and improved existing management applications using PHP CodeIgniter 3, JQuery, and Microsoft SQL Server. Implemented new features and optimized database queries.",
    tags: ["PHP CodeIgniter 3", "JQuery", "Microsoft SQL Server"],
    link: "https://wms.k-linkindo.co",
    github: "https://github.com/K-Link-Indonesia/wms-2026",
  },
  {
    title: "Shipment Service Backend (V1 & V2)",
    company: "K-Link Indonesia",
    description: "Refactored the original Node.js/Sequelize monolithic backend into modular NestJS/Prisma architecture with role-based access, multi-status tracking, and automated scheduling for airwaybill statuses.",
    tags: ["NestJS", "Prisma", "Node.js", "Sequelize"],
    link: "#",
    github: "https://github.com/K-Link-Indonesia/shipping_service",
  },
  {
    title: "Dashboard Shipment Service",
    company: "K-Link Indonesia",
    description: "Built an admin dashboard using Next.js, TailwindCSS, and shadcn to monitor shipment logistics, integrating real-time data updates and chart analytics.",
    tags: ["Next.js", "TailwindCSS", "shadcn"],
    link: "https://dashboard-shipping-service.k-linkindo.co",
    github: "https://github.com/K-Link-Indonesia/shipping_service_dashboard",
  },
  {
    title: "Sales Management System",
    company: "K-Link Indonesia",
    description: "Developed an e-commerce management platform utilizing React.js, TypeScript, Golang, and Chakra UI for distributors to manage sales data, ranks, commission statuses, and downlines.",
    tags: ["React.js", "TypeScript", "Golang", "Chakra UI"],
    link: "https://dcmy-v2-dev.k-link.us",
    github: "https://github.com/K-Link-Indonesia/data-center-malaysia-fe_v2",
  },
  {
    title: "Backend Message Service",
    company: "K-Link Indonesia",
    description: "Developed a unified messaging and notification REST API service using Go, Gin, and GORM with PostgreSQL. Managed asynchronous outbound messaging for WhatsApp and SMS using RabbitMQ. Integrated providers like Jatis, WAHA, and Green API, including template management, media uploads to S3, and webhook processing.",
    tags: ["Go", "Gin", "GORM", "PostgreSQL", "RabbitMQ", "REST API", "WAHA", "Jatis", "Green API", "S3"],
    link: "#",
    github: "https://github.com/K-Link-Indonesia/service-message",
  },
  {
    title: "EMS Application",
    company: "Freelance",
    description: "Engineered a fleet monitoring application for gas trucks utilizing NestJS, Next.js, and PostgreSQL to track vehicle movement, attendance data, and admin management.",
    tags: ["NestJS", "Next.js", "PostgreSQL"],
    link: "https://ineko.up.railway.app",
    github: "https://github.com/icaddddd/backend_ems",
    github2: "https://github.com/icaddddd/web_ems",
  },
  {
    title: "E-Commerce Lakoe",
    company: "Dumbways.id",
    description: "Collaborated in a team using Remix to deliver a high-performance e-commerce platform combining captivating design with advanced functionality to meet customer needs.",
    tags: ["Remix"],
    link: "#",
    github: "https://github.com/icaddddd/lakoe-deploy-icad",
  },
  {
    title: "Geospatial LLM Integration Application",
    company: "Personal Project",
    description: "Built a fullstack JavaScript application integrating a local LLM with Google Maps APIs to process user queries and visualize structured geographic data.",
    tags: ["JavaScript", "LLM Integration", "Google Maps API"],
    link: "#",
    github: "https://github.com/icaddddd/LLM_Local_Google_maps_backend",
    github2: "https://github.com/icaddddd/LLM_Local_Google_maps_frontend",
  },
  {
    title: "Learning Management System (LMS) Backend",
    company: "Freelance",
    description: "Maintained and debugged a Learning Management System backend (dev-innovate.scalastaging.online) built with Express.js and PostgreSQL.",
    tags: ["Express.js", "PostgreSQL"],
    link: "#",
    github: "#",
  },
  {
    title: "Twitter/X Clone (Circle)",
    company: "Dumbways.id",
    description: "Created a simplified social media clone focused on circle-based posting using React.js, TypeScript, Chakra UI, and PostgreSQL, complete with timeline feeds and local storage persistence.",
    tags: ["React.js", "TypeScript", "Chakra UI", "PostgreSQL"],
    link: "#",
    github: "https://github.com/icaddddd/Circle",
  },
  {
    title: "Backend Ticketing Project Service",
    company: "Freelance",
    description: "Developed a scalable microservice for a ticketing platform using NestJS, PostgreSQL, and Prisma, handling event creation, ticket purchasing, and QR-code validation logic.",
    tags: ["NestJS", "PostgreSQL", "Prisma"],
    link: "#",
    github: "#",
  },
  {
    title: "POS (Point of Sales) Website",
    company: "Freelance",
    description: "Developed a frontend POS web application using React.js, TypeScript, and Chakra UI, featuring product listings, a cart system, and an order summary to simulate cashier functionality.",
    tags: ["React.js", "TypeScript", "Chakra UI"],
    link: "#",
    github: "#",
  },
  {
    title: "Event Organizer Landing Page",
    company: "Freelance",
    description: "Developed a responsive, SEO-friendly landing page with dynamic routing using React.js, TypeScript, and Chakra UI.",
    tags: ["React.js", "TypeScript", "Chakra UI"],
    link: "https://samakami.id",
    github: "https://github.com/icaddddd/samakami_new",
  },
  {
    title: "Personal Portfolio Page",
    company: "Freelance",
    description: "Designed a responsive static page using semantic HTML and CSS to showcase personal information, experience, and project links.",
    tags: ["Next.js", "Tailwind CSS", "TypeScript", "shadcn/ui"],
    link: "https://rhisjad-djavatri.site",
    github: "https://github.com/icaddddd/portofolio-landing-page",
  },
  {
    title: "Data Center Malaysia Frontend (V2)",
    company: "K-Link Indonesia",
    description: "Developed and maintained the frontend architecture for the Malaysia data center project, focusing on user details and nexus member management using Vue.js.",
    tags: ["React.js", "Typescript", "Chakra UI"],
    link: "https://dcmy-v2-dev.k-link.us",
    github: "https://github.com/icaddddd/data-center-malaysia-fe_v2",
  },
  {
    title: "Automated Log Management System",
    company: "K-Link Indonesia",
    description: "Developed a specialized cron schedule within a Next.js and Prisma environment to automate the deletion of activity logs older than three months.",
    tags: ["Next.js", "Prisma", "Cron"],
    link: "#",
    github: "#",
  },
  {
    title: "Cake Stock Management (Warung Sehati)",
    company: "Freelance",
    description: "A Stock Management Web Application designed for cake bakery business to monitor stock. Integrated with Telegram Bot for easy access.",
    tags: ["Next.js", "Prisma", "Tailwind CSS", "Telegram Bot"],
    link: "https://warung-sehati-testing.up.railway.app",
    github: "https://github.com/icaddddd/cake-stock",
  },
  {
    title: "Cash Flow Management (Bakery)",
    company: "Freelance",
    description: "A Cash Flow Management Web Application designed for bakery business to monitor cash flow.",
    tags: ["Next.js", "Prisma", "Tailwind CSS"],
    link: "#",
    github: "https://github.com/icaddddd/bakery-cash-flow",
  },
];

export const certifications = [
  {
    id: 1,
    title: "Dumbways Certificate of Completion",
    issuer: "Dumbways.id",
    date: "December 2023",
    credentialUrl: "/certificate-dumbways.pdf",
  },
];
